### ISSUE TITLE
Why CS61B is not included？

### ISSUE THREAD

**Issue by QS0x01** [Developer-Y/cs-video-courses#125]
Take the liberty to ask~ What are the rules for inclusion？（Translated by Google）

Is the following the reason?

> One philosophy used in this list while integrating MOOCs is that link should directly point to videos for viewing/downloading than registration and waiting for the next session. If videos are directly accessible through the platform/youtube or any other source, please use the direct source. This is list of video courses, not a list of MOOCs.

**Comment by Developer-Y** [comment]
It was present before but I guess original link broke due to Berkeley policies and link was removed. Please feel free to add it via PR or I will add it when I find a suitable link.

Regards,
