### ISSUE TITLE
Link broken for Quantum Mechanics for Scientists and Engineers

### ISSUE THREAD

**Issue by Krushang-Shah** [Developer-Y/cs-video-courses#127]
YouTube playlist does not exist for [Quantum Mechanics for Scientists and Engineers](https://www.youtube.com/playlist?list=PL_onPhFCkVQi2O405SkNf3hv-7HXnZnMm)

**Comment by Developer-Y** [comment]
I do not have a new link which works, if you have one please create a pull request. Closing the issue for now.
