### ISSUE TITLE
How to learn

### ISSUE THREAD

**Issue by PotatoLuffy** [Developer-Y/cs-video-courses#146]
Every topic have so many source,  how to learn it.

**Comment by dev-nolant** [comment]
Find a path you're interested in first(Software Engineering, Artificial Intelligence, Machine Learning, etc.).

Once you find that path, I recommend looking into it a little on your own to get an idea of what you'd be doing, and then come back later on to watch some videos on your chosen path!

Start with the introduction videos for the path you choose. Then move on to the more advanced videos progressively. 

You don't have to stay on that path either, if you find that you don't like it, you can always choose a different one.

You got this!

**Comment by morphean-sec** [comment]
Starting with CS50 is a solid choice. Very beginner friendly and quality content...plus it's taught by Harvard professors.

**Comment by harshsingh32** [comment]
Start with cs50 is definitely 😁 a good choice, although most of the content is beginner friendly but cs50.

**Comment by roystonlmq** [comment]
I would begin with CS50P -> CS50X -> CS50W

**Comment by thenoblet** [comment]
I'd say start with CS50x. I took and it's the best decision I made in my programming journey. Fully recommend you start from there. The course is a little difficult but worth it.

**Comment by retrogtx** [comment]
Start with the cs50 course, then one by one go as suggested by the repo in the field you are interested in..!

**Comment by thenoblet** [comment]
> Start with the cs50 course, then one by one go as suggested by the repo in the field you are interested in..!

Right!
