### ISSUE TITLE
Being up to date

### ISSUE THREAD

**Issue by gamstc** [Developer-Y/cs-video-courses#16]
Dear Developer-Y, 
Thank you so much for this wonderful list! I am running the CS department at [Kiron Open Higher Education](https://kiron.ngo/about), an online study platform for refugees. A comprehensive list like this is essential for our curriculum. 
However, I have noticed that many items on the list are a little outdated. Would you be interested in working together with us to expand and update the list? Or do you just want to rely on word-of-mouth and random contributions here?
Looking forward to hearing from you!

**Comment by Developer-Y** [comment]
Thank you for reaching out. There are ample resources available online and which courses are appropriate or obsolete tends to be subjective opinions. There are many classical lectures by top professors which do not yet have comparable recent versions.

Please feel free to use the links for helping your group.

**Comment by gamstc** [comment]
Thank you for your response!
We are of course using all the resources out there (class-central, NPTEL, saylor.org, etc.). However, I believe the expertise here on github can be a valuable addition to finding more hidden MOOCs. Thanks again for making this happen.
