### ISSUE TITLE
Broken Link in Blockchain Development section

### ISSUE THREAD

**Issue by ashishlamsal** [Developer-Y/cs-video-courses#195]
The third course [Cryptocurrency Engineering and Design - Spring 2018 - MIT](https://ocw.mit.edu/courses/media-arts-and-sciences/mas-s62-cryptocurrency-engineering-and-design-spring-2018/lecture-videos/) under subsection **Blockchain and Cryptocurrencies** of section [Blockchain Development](https://github.com/Developer-Y/cs-video-courses#blockchain-development) results in _page not found._

I guess, the correct link is:
https://ocw.mit.edu/courses/mas-s62-cryptocurrency-engineering-and-design-spring-2018/video_galleries/lecture-videos/

**Comment by Developer-Y** [comment]
MIT OCW has recently changed their whole website, due to this possibly many MIT OCW links may not be working currently. I will look into how to update all the broken links, would be better if there is a pattern to switch between old and new links.
