### ISSUE TITLE
[Adding course] - CS253 Stanford - Web Security

### ISSUE THREAD

**Issue by MaximilianFreitag** [Developer-Y/cs-video-courses#198]
This is the whole course of the Stanford web security course CS253 made in 2019. The tutor explains common cyber attacks and how to prevent them in the first place. You can add the course in your security section.

https://www.youtube.com/playlist?list=PLMF2PpA06Sb26oYT-dfNOt3Y4wwoLAho0

**Comment by Developer-Y** [comment]
Added, thanks for sharing.
