### ISSUE TITLE
(Discrete Mathematics and Mathematical Reasoning 2015) page is not available

### ISSUE THREAD

**Issue by Abdelrahman-Kh-Fouad** [Developer-Y/cs-video-courses#208]
[Discrete Mathematics and Mathematical Reasoning 2015/16 - University of Edinburgh](http://groups.inf.ed.ac.uk/vision/VIDEO/2015/dmmr.htm)
the link in math for computer scientists section.

**Comment by SquidOfDoom** [comment]
the correct link is: https://www.inf.ed.ac.uk/teaching/courses/dmmr/
