### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by stereobooster** [Developer-Y/cs-video-courses#26]
This is super cool repository. Big thanks for collecting this all

I would add words by Hal Abelson in the beginning of this document (This is from his first lecture in SICP):

> Computer science is a terrible name for this business. First of all, it's not a science. It might be engineering or it might be art, but we'll actually see that computer so-called science actually has a lot in common with magic... So it's not a science. It's also not really very much about computers. And it's not about computers in the same sense that physics is not really about particle accelerators, and biology is not really about microscopes and petri dishes. And it's not about computers in the same sense that geometry is not really about using surveying instruments.

It would be helpful to see roadmap of courses. Some courses have prerequisites (other courses or books). If we can list them, say as dot file, we can generate SVG graph with graphviz

Offtopic: separate repo with computer science papers. Like:
 - http://blog.fogus.me/2011/09/08/10-technical-papers-every-programmer-should-read-at-least-twice/
 - http://paperswelove.org/

**Comment by Developer-Y** [comment]
It's a good idea and would be helpful especially for students/non-CS self learners. Many Universities already have some sort of dependency graphs for their students, for example [this link at UMN](https://www.cs.umn.edu/sites/cs.umn.edu/files/cseprerequisite_chart.pdf). 

Instead of reinventing the wheel,  it's better to point to such sample charts. IMO it would be better to add such links along with misc notes instead of adding directly to the README file

**Comment by stereobooster** [comment]
Yep, makes sense. Found those:

 - https://ocw.mit.edu/courses/mit-curriculum-guide/
 - https://www.eecs.mit.edu/curriculum2016
 - http://csmajor.stanford.edu/ProgramSheets.shtml

**Comment by Developer-Y** [comment]
Added to [NOTES.md](https://github.com/Developer-Y/cs-video-courses/blob/master/NOTES.md)

**Comment by stereobooster** [comment]
I started my project for collecting computer science videos https://github.com/stereobooster/cs-video/ , which are not series of lectures, but rather talks on conferences or interviews, but not less valuable. Check it out

**Comment by Developer-Y** [comment]
Great initiative, keep sharing.
