### ISSUE TITLE
"CS 164 Software Engineering - Harvard" hyperlink is not working

### ISSUE THREAD

**Issue by tan-i-ham** [Developer-Y/cs-video-courses#268]
http://cs164.tv/2014/spring/ is not available

https://github.com/Developer-Y/cs-video-courses/blob/f7c737539dc852e3497707c54465bc475cb1ba45/README.md?plain=1#L225

**Comment by yugborana** [comment]
@Developer-Y i would like to contribute if you could assign

**Comment by yugborana** [comment]
i am adding a youtube video link in this code and pulling a request, merge if you find it correct
