### ISSUE TITLE
Query for new topic.

### ISSUE THREAD

**Issue by vikaskyadav** [Developer-Y/cs-video-courses#28]
Is Discrete Mathematics/ Discrete Structures also a part of Mathematics portion?

**Comment by Developer-Y** [comment]
Yes. usually discrete math covers Induction, Sets,Combinatorics, Probability, Number Theory along with basic Graph theory and few other concepts. Considering there are currently only 3 courses on this topic, it's better to keep them with other Math courses. Infact title of notes that are part of MIT's 6.042 is also Math for Computer Science

**Comment by vikaskyadav** [comment]
Cool!
You can also include video lectures from www.nptel.ac.in, if you want to. Some of them too are too good.

**Comment by Developer-Y** [comment]
There are many courses at NPTEL, that is why it is added as top level link. If you are familiar with which are the great courses in NPTEL, please fee free to add them through a pull request.
