### ISSUE TITLE
New way of presenting the given course lists.

### ISSUE THREAD

**Issue by yugborana** [Developer-Y/cs-video-courses#281]
I would like to put forward the thought of arranging the courses in the tabular form with course name, course thumbnail and course link in respective columns for respective topics like databases, algorithms, etc. It will be more user friendly and easy to connect.

**Comment by Developer-Y** [comment]
Thanks for the suggestion, I am sure there are many ways to make it look good but it will be hard to maintain. Everyone who wants to contribute will have to learn the format. That is why I have kept it to most basic markdown only.

Regards,

**Comment by yugborana** [comment]
yeah correct. Thanks for reverting back
