### ISSUE TITLE
Fucking CMU's Intermediate Statistics Course Doesn't Have a Playlist

### ISSUE THREAD

**Issue by ceberous** [Developer-Y/cs-video-courses#29]
So I made one for the fucking dumb ass that didn't. Also, google, in all your magnificence, where the fuck is an automated playlist generator ? They have fucking dates in the title. You would think youtube, by now, would be like "oh hey, here is a suggested playlist from the videos you just uploaded".

https://www.youtube.com/playlist?list=PLcW8xNfZoh7eI7KSWneVWq-7wr8ffRtHF

**Comment by Developer-Y** [comment]
Thanks, playlist added along with the course link.
