### ISSUE TITLE
Gödel, Escher, Bach: A Mental Space Odyssey

### ISSUE THREAD

**Issue by stereobooster** [Developer-Y/cs-video-courses#31]
https://ocw.mit.edu/high-school/humanities-and-social-sciences/godel-escher-bach/video-lectures/

Haven't found good video playlist on YouTube just yet.

**Comment by Developer-Y** [comment]
These lectures seem to fall more towards general talks about multiple topics than core CS topics, have added them to list [the-talks](https://github.com/Developer-Y/the-talks) which is intended for in general classical lectures/tech-talks
