### ISSUE TITLE
Hamming, Intro to The Art of Doing Science and Engineering: Learning to Learn

### ISSUE THREAD

**Issue by stereobooster** [Developer-Y/cs-video-courses#32]
[This playlist](https://www.youtube.com/watch?v=AD4b-52jtos&list=PL2FF649D0C4407B30) seems to contain some videos out of course. 

P.S. this is the same Hamming which invented Hamming code.

**Comment by Developer-Y** [comment]
It's a good playlist, however these videos fall on more towards general talks than core computer science. This playlist is already part of [the-talks](https://github.com/Developer-Y/the-talks) which is general collection of classic motivational/technical/managerial/entrepreneurial/etc talks.
