### ISSUE TITLE
Course naming consistency 

### ISSUE THREAD

**Issue by david-ooooh** [Developer-Y/cs-video-courses#331]
Example: CS50, CS 50
It is a small thing but the naming of the course numbers seems inconsistent.
Some have a space between the number and the subject abbreviation and some don't.
It would be nice to have consistency for control + F users.

**Comment by Developer-Y** [comment]
I can understand your concern, when this repo was started there was a naming convention. But over period of time many people have contributed and I don't want to turn away valuable contribution for naming convention. Many links may not follow a pattern but most links are still readable. 

Regards,
