### ISSUE TITLE
Create a math-video-courses

### ISSUE THREAD

**Issue by EugenHotaj** [Developer-Y/cs-video-courses#38]
This is a very resources and I've used it to find some nice lectures on RL. I think the logical extension is to also include math courses, maybe in a different folder or repository.

**Comment by Developer-Y** [comment]
For math topics that are usually required by CS students, there is a section at https://github.com/Developer-Y/cs-video-courses#math-for-computer-scientist.

If you are talking about exclusive math repo, there is already one at -> https://github.com/Developer-Y/math-science-video-lectures , it needs more structuring and more courses though.

If you have any math courses that You believe should be added there, please feel free to create a pull request or let me know to add them.

**Comment by EugenHotaj** [comment]
Yes the math-science-video-lectures is exactly what I had in mind. Didn't realize it existed, thanks! I'll be sure to add any interesting ones I come across.
