### ISSUE TITLE
UC Berkeley course videos to be taken offline on 15th March 2017

### ISSUE THREAD

**Issue by Developer-Y** [Developer-Y/cs-video-courses#47]
All,

FYI, effective 15th March 2017 UC berkeley will remove its course content from Youtube and iTunes. 

Source:
https://www.youtube.com/user/UCBerkeley
http://news.berkeley.edu/2017/02/24/faq-on-legacy-public-course-capture-content/

Q: What will happen to the recordings?

A: Beginning March 15, 2017, iTunesU Course Capture content will be removed. You may continue to use/download course capture content until that date.

**Comment by eternalfool** [comment]
Some links are deal now.
[CS 186](https://www.youtube.com/playlist?list=PL-XXv-cvA_iBVK2QzAV-R7NMA1ZkaiR2y)

Some lectures can be found in the archive like [here](https://archive.org/details/UCBerkeley_Course_Computer_Science_186).

**Comment by nuaajeff** [comment]
Is there anyone who has downloaded cs 189 TAT... I'm so sad that this course can not be found on the Internet anymore...

**Comment by Developer-Y** [comment]
As per [lbry blog post](https://lbry.io/news/20000-illegal-college-lectures-rescued), lbry has downloaded all the videos and made them available for public.

If CS 189 lectures are not present there, please update here so that anyone with other link may post it.

**Comment by Developer-Y** [comment]
This link at archive.org points to 423 collections of UC Berkeley lectures.
https://archive.org/search.php?query=UCBerkeley&and%5B%5D=mediatype%3A%22collection%22

**Comment by rhamidon** [comment]
I could only find CS188!
Does anyone has CS189 lecture videos?

**Comment by garfieldnate** [comment]
I'm looking for Ren Ng's CS 184 lectures. I cannot find them on LBRY or archive. Here's the course webpage: https://cs184.eecs.berkeley.edu/.

**Comment by jalotra** [comment]
> I could only find CS188!
> Does anyone has CS189 lecture videos?

@rhamidon Did you find the video lectures for Cs 189?

**Comment by rhamidon** [comment]
> Cs 189

Sorry, I did not

**Comment by rhamidon** [comment]
@jalotra nope. Wasn't able to find. Didn't follow up on them. Were you able to find latest versions?

**Comment by Franklin257** [comment]
> Is there anyone who has downloaded cs 189 TAT... I'm so sad that this course can not be found on the Internet anymore...
