### ISSUE TITLE
Sedgewick Algorithms videos are gone

### ISSUE THREAD

**Issue by morningscifi** [Developer-Y/cs-video-courses#52]
I believe those lectures are mirrored here:

https://www.youtube.com/playlist?list=PLxc4gS-_A5VDXUIOPkJkwQKYiT2T1t0I8

The account in question, however, does not appear to actually own the copyright on the videos. I believe the original videos should be accessible directly through the Coursera algorithms course:

https://www.coursera.org/learn/algorithms-part1

**Comment by Developer-Y** [comment]
Thanks for the update, I wasn't able to find direct link to videos shared by Profs/University/Coursera, removed non-working links for now.
