### ISSUE TITLE
MOOC - Natural Language Processing, Dan Jurafsky & Chris Manning - Coursera link died

### ISSUE THREAD

**Issue by gofortargets** [Developer-Y/cs-video-courses#59]
The link of MOOC - Natural Language Processing, Dan Jurafsky & Chris Manning - Coursera had died. Can you find the alternative? Thank you.

**Comment by Developer-Y** [comment]
http://academictorrents.com/details/d2c8f8f1651740520b7dfab23438d89bc8c0c0ab

I have not validated it, just found it online.
