### ISSUE TITLE
Not readable

### ISSUE THREAD

**Issue by vsouto** [Developer-Y/cs-video-courses#9]
I tried opening one "course", but turned out to be a completly 23 pages illegible PDF . 

Something like a student taking notes from an advanced class.
Not trying another one.

Was this one:
https://electures.informatik.uni-freiburg.de/portal/web/guest/detail/-/modulnavigation/view/3013/10069/

**Comment by Developer-Y** [comment]
ELectures for Universität Freiburg courses are divided into sections at left panel. If you click at course title at the top, it will list all slides and lectures in 1 page. For above course, you can access videos by going to sections for which videos are present or though this direct link
https://electures.informatik.uni-freiburg.de/portal/web/guest/detail/-/modulnavigation/view/3013?_EXT_MODULNAVIGATION_LIFERAY_SHARED_nestedsetId=

Some videos on Universität Freiburg are encoded through Camtasia or Lecturnity, please use a video player accordingly. Will add this as footnote for reference. Hope this helps

**Comment by Developer-Y** [comment]
Closing the issue.
