### ISSUE TITLE
Courses with login pages

### ISSUE THREAD

**Issue by LameLemon** [Developer-Y/cs-video-courses#99]
Some courses have login pages so that only students of the institution can view the material. Should these courses be left on the list or should they be taken out seeing that they cannot be accessed by the general public?

**Comment by Developer-Y** [comment]
Hi, when this repo was created, most course pages had direct access. It is possible that they may have been moved behind some authentication scheme for the newer version of courses. We can remove such courses. Its just that list has grown so long that it is cumbersome to find out broken links.

**Comment by LameLemon** [comment]
I see, in that case, if I come across any such courses, I'll try to find replacements and if none exists I'll make sure to take them out.

**Comment by lflucasferreira** [comment]
I found this one that requires me to login first:
https://courses.engr.illinois.edu/cs446/sp2019/AGS/_site/
